// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCBPa1e8DDS7QWB9GaL7tj4gFl23y4WSq8',
    appId: '1:288597580795:web:7fe1e25aac14db0883895e',
    messagingSenderId: '288597580795',
    projectId: 'grad-project-ver-1',
    authDomain: 'grad-project-ver-1.firebaseapp.com',
    storageBucket: 'grad-project-ver-1.firebasestorage.app',
    measurementId: 'G-PZR2M76FDP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlZUiN61HjEZe6AA1s2KVNKZFLaCIKxDI',
    appId: '1:288597580795:android:20843f80f8c9581f83895e',
    messagingSenderId: '288597580795',
    projectId: 'grad-project-ver-1',
    storageBucket: 'grad-project-ver-1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMbgcG-NUODZCky8QkUQM-OmdvobHllRQ',
    appId: '1:288597580795:ios:3207c5c7d4bbfa2283895e',
    messagingSenderId: '288597580795',
    projectId: 'grad-project-ver-1',
    storageBucket: 'grad-project-ver-1.firebasestorage.app',
    iosBundleId: 'com.example.gradProjectVer1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMbgcG-NUODZCky8QkUQM-OmdvobHllRQ',
    appId: '1:288597580795:ios:3207c5c7d4bbfa2283895e',
    messagingSenderId: '288597580795',
    projectId: 'grad-project-ver-1',
    storageBucket: 'grad-project-ver-1.firebasestorage.app',
    iosBundleId: 'com.example.gradProjectVer1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCBPa1e8DDS7QWB9GaL7tj4gFl23y4WSq8',
    appId: '1:288597580795:web:2504bfe9fe6b0ba883895e',
    messagingSenderId: '288597580795',
    projectId: 'grad-project-ver-1',
    authDomain: 'grad-project-ver-1.firebaseapp.com',
    storageBucket: 'grad-project-ver-1.firebasestorage.app',
    measurementId: 'G-N851W3CZ7S',
  );
}
